<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Post;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\JsonResponse;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function createPost()
    {  
        $em = $this->getEntityManager();

        $post = new Post();
        $post->setContent('Message');
        $post->setDate(new \DateTime('2014-01-01 00:00:00'));
        $post->setAuthor('You');

        $em->persist($post);
        $em->flush();

        return new Response('Saved new post with id '.$post->getId());
    }


    public function save(Post $post)
    {
        $em = $this->getEntityManager();
        $em->persist($post);
        $em->flush();
    }

    public function getPosts()
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery("select p from AppBundle\Entity\Post p");
        $posts = $query->getArrayResult();

        return $posts;
    }

    public function getPostsFromAuthor($author)
    {
        $posts = $this->createQueryBuilder('q')
        ->andwhere('q.author = :author')
        ->setParameter('author', $author)
        ->getQuery()
        ->getArrayResult();
        return $posts;
    }
    public function getPostsFromTo($from,$to)
    {
        $posts = $this->createQueryBuilder('q')
        ->andwhere('q.author = :author')
        ->setParameter('author', $author)
        ->getQuery()
        ->getArrayResult();
        return $posts;
    }
    public function getPostsFromId($id)
    {
        $em = $this->getEntityManager();
        $posts = $em->find('AppBundle:Post', $id);
        return $posts;
    }
}
