<?php

namespace AppBundle\Repository;

use AppBundle\Entity\VdmEntity;
use Symfony\Component\HttpFoundation\Response;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Common\Persistence\ManagerRegistry;

/**
 * VdmEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VdmEntityRepository extends \Doctrine\ORM\EntityRepository
{

    public function createAction()
    {  
        $em = $this->getEntityManager();

        $vdmentity = new VdmEntity();
        $vdmentity->setContent('Message');
        $vdmentity->setDate('2017');
        $vdmentity->setHour('10:00');
        $vdmentity->setAuthor('Me');

        // tells Doctrine you want to (eventually) save the vdmentity (no queries yet)
        $em->persist($vdmentity);

        // actually executes the queries (i.e. the INSERT query)
        $em->flush();
        var_dump($vdmentity);

        return new Response('Saved new vdmentity with id '.$vdmentity->getId());
    }

    public function listAllVdm()
    {  
        $em = $this->getEntityManager();

        $query = $em->createQuery("select v from AppBundle\Entity\VdmEntity v");
        $vdmentity = $query->getResult();
        var_dump($vdmentity);

        return new Response('List of vdm entities');
    }

}
